baseURL = 'https://timberlovingcare.com/'
CF_PAGES_URL = 'https://timberlovingcare.com'
languageCode = 'en-us'
title = 'Timber Loving Care'
theme = 'tailbliss'

[params]
  description = "Arborist & Wildfire Mitigation Services and Offering Wood of Unique Character."
  author = "Timber Loving Care"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
